README.md
docs/automation-actions.md
docs/examples.md
docs/filter-functions.md
docs/troubleshooting.md

You guys rock! Really love using this.

Went through the docs and fixed some small typos

---

.github/workflows/gitstream.yml
docs/downloads/gitstream.yml

fix indentation

---

docs/downloads/approvals.cm
docs/downloads/code-experts.cm
docs/downloads/javascript.cm
docs/downloads/labels.cm
docs/downloads/organization.cm
docs/downloads/python.cm
docs/examples.md
mkdocs.yml

This PR condenses the example library down to a smaller number of more comprehensive examples. It includes the vast majority of existing examples with the addition of some from the [automations directory of the gitStream repo](https://github.com/linear-b/gitstream/tree/main/automations).

Example library

---

docs/github-installation.md

New tip: **Connect repositories**

new tip for org level setup

---

docs/how-it-works.md

This change matches the language we use everywhere else in the docs.

Change Accessory Expression to Custom Expression

---

docs/downloads/labels.cm

The comments for the missing_tests automation need to be updated to match some recent changes.

Correct comment information

---

.cm/gitstream.cm
README.md

Change automation to encourage screenshots 

---

docs/github-installation.md
docs/gitlab-installation.md

uninstall instructions details for GitLab

---

automations/approve_safe_changes/README.md
automations/approve_safe_changes/approve-safe-changes.cm

Update Safe Changes Example

---

.github/ISSUE_TEMPLATE/new_automation_example.md
docs/automations/automation-library.md

This template makes it easy for people to contribute their automation ideas to our library.

Create new automation example issue template.

---

docs/context-variables.md

Added:
| Values             | Type      | Description                                              |
|--------------------|-----------|-------------------------------------------------|
| `pr.status` | String | The PR status: `open`, `closed` and **`merged`** |
| `pr.requested_changes` | [String] | List of users that requested changes |

added merged status and open request changes to pr context

---

docs/custom-filters-v1.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1bHitkeNFlsmseFE5uyZX9mnbc0G945Y%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=geRgLGC)
* formatting changes
* added basic filter example

Basic example

---

docs/cm-file.md

Add documentation on how to mix and control global and repo rules

---

docs/automations/approve-team-by-directory/README.md

This renames the title from Approve Team by Directory to Approve Expert Team.

Rename automation title.

---

docs/downloads/automation-library/approve-safe-changes.cm

This adds the use of allImages to the safe_changes example.

add allImages filter function

---

docs/context-variables.md

The list around objects is missing - fixed.

add list indicator

---

.cm/gitstream.cm
docs/index.md

have each image and text wrapped in single frame

---

docs/downloads/automation-library/approve-safe-changes.cm

Fixing https://github.com/linear-b/gitstream/issues/179

fix example that have every after boolean checks

---

docs/filter-functions.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19eCCCVDhBPiJWRf13w4L8ZRvOkTUZFS5k%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=GWXKkRT)

Map to enum documentation

---

docs/how-it-works.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1uSMGhr1Qgnz424JMN3786xJzh4MdiOy4%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=gu2s2rG)

added filters to reserved words and rearrange

---

docs/context-variables.md

explain how to use branch.diff.files_metadata

---

docs/filter-functions.md
docs/index.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX193kzu5FeBaRJ7Jw5mOMpyXJtIZOUnLWs4%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=sekFd72)

added mention for unsupported by gitlab

---

docs/automations/additional-review-for-large-pr/README.md

fix typo in Additional Review for Large PRs

---

docs/cm-file.md

explain ignore files

---

docs/gitlab-installation.md
docs/index.md
mkdocs.yml

Gitlab install changes

---

docs/automation-actions.md
docs/filter-functions.md

issue https://github.com/linear-b/gitstream/issues/197
added action explain-code-experts
added link from explainCodeExperts

action explain-code-experts

---

docs/context-variables.md

issue: https://github.com/linear-b/gitstream/issues/153

add context to pr: unresolved_threads

---

docs/downloads/automation-library/assign_code_experts.cm
docs/downloads/gitstream.cm

fix CM syntax error

---

docs/execution-model.md

trigger on comments

---

docs/context-variables.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19LlVSQsBamikieJa4lmRPuMnj5qBsVf5E%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=qeZzD8e)

added author_is_org_member

---

docs/automation-actions.md

support explain-code-experts for gitlab

---

docs/automation-actions.md
docs/cm-file.md
docs/context-variables.md
docs/dry-run-mode.md
docs/examples.md
docs/faq.md
docs/filter-functions.md
docs/github-installation.md
docs/gitlab-installation.md
docs/how-it-works.md
docs/index.md
docs/integrations/dependabot.md
docs/integrations/javadoc.md
docs/integrations/jira.md
docs/integrations/jit.md
docs/integrations/jsdoc.md
docs/integrations/sonar.md
docs/integrations/swimm.md
docs/quick-start.md
docs/troubleshooting.md

The docs site has some SEO health issues resulting from missing meta descriptions and 404 links. I added meta descriptions to all the major pages, and we should add them by default for all pages moving forward.

Fix SEO Issues

---

docs/automations/automation-library.md
docs/integrations/README.md

This reorganizes the automation library page and injects the integrations page at the bottom.

Add Integrations to automation library.

---

docs/troubleshooting.md

troubleshooting missing CI file message

---

docs/troubleshooting.md

fix you -> I

---

docs/filter-functions.md

fix of nope logic - true on empty lists

---

docs/context-variables.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1TGVu8zpyEZj6bHUuXAJt7NqYNOBTuPSY%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=7i40Gm0)

added owner

---

docs/automation-actions.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19dej8g2J2VLGCVtsNLKkM4QJI79LBc%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=2TMHpQn)

added wait-foar-all-checks arg

---

docs/filter-functions.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18KB7MexyNN1c8K61IwjkUlyiNW2Zjlwc%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=mnuWru_)

added capture filter

---

docs/automation-actions.md
docs/execution-model.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1993POnw6wEwe0fUhMNUOUQwQz6pN3ilk%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=RD0s9tK)

Selective ci

---

docs/automation-actions.md
docs/execution-model.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18PoK37uCXK1ZufLOsqsfYzJrZ6tcrvDBU%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=_XpxeLE)

text fixes

---

docs/automation-actions.md
docs/context-variables.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18nvq4A8Cr3l2sT9TgS53T89veUPMk1Xg%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=-wxFqjO)

add conflicted_files_count and minor changes

---

docs/automation-actions.md
docs/context-variables.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1Usxg9cyc9oFuUiIkqEMoE475qyPx6RU%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=xwTPRnd)

added slack action + fixed env variable description

---

docs/filter-functions.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18RHsiMQU5NKH7gZV9TCKANKAPSkmsQ%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Iw_EBEr)

fixed jit example

---

docs/filter-functions.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18l4OKDaCkkMvML6VZzuuWNIxVskUMm0%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=VRHVPCa)

removed glob

---

docs/context-variables.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1Jzgu095rD4KIYxxXIN8RWO2w9qRaGwhM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=MVG7sEy)

added pr number

---

docs/context-variables.md

add repo visibility

---

docs/automation-actions.md

checks are completed with conclusion

---

docs/downloads/automation-library/integrations/github-actions/dispatch-github-action/dispatch_github_action_branch.cm

fix expression

---

.github/workflows/github-repo-stats.yml

I'm implementing this based on this resource: https://github.com/jgehrcke/github-repo-stats/wiki/Tutorial

Create Repo Stats Tracking Workflow

---

docs/downloads/automation-library/standard/gitstream_starter.cm
docs/examples.md
mkdocs.yml

Create new starter example

---

README.md

This PR makes major updates to the repo's Readme.

Revamp Readme

---

docs/downloads/gitstream.cm

This updates the default gitStream config we show users during the gitStream installation process.

Update use cases for default gitStream config

---

docs/github-installation.md

steps for self hosted

---

plugins/filters/extractOrcaFindings/README.md

fix order of lines

---

docs/how-it-works.md

This improves the section in How gitStream works that covers the built-in functions and moves the content higher in the guide to provide better explanation to newcomers.

Built in functions

---

docs/automations/integrations/dependabot/approve-dependabot/README.md

Remove use of `http://127.0.0.1:8000` in link

Fix dependabot page

---

docs/automations/integrations/slack/slack-auto-recognition/README.md
docs/automations/integrations/slack/slack-send-notification/README.md

This make the images and config description appear a bit better.

Small fix to Slack page.

---

docs/automations/integrations/terraform/review-new-module/README.md
docs/automations/integrations/terraform/review-terraform-module-name/README.md
docs/automations/integrations/terraform/review-terraform-source-version/README.md
docs/automations/integrations/terraform/review-terraform/README.md

fix missing desc in Teraform automations

---

docs/downloads/automation-library/integrations/copilot/label_copilot_by_prompt.cm
docs/execution-model.md

added column: defaults

---

docs/automations/integrations/copilot/flag-copilot-pr/README.md
docs/downloads/automation-library/integrations/copilot/label_copilot_by_tag.cm

Fix copilot link

---

docs/execution-model.md

execution model changes

---

docs/changelog.md
docs/execution-model.md

documenting comment edit trigger

---

docs/automation-actions.md
docs/changelog.md

document GitLab request-changes

---

docs/automations/integrations/azure-boards/link-azure-boards/README.md
docs/automations/integrations/jira/label-missing-jira-info/README.md
docs/automations/integrations/jira/link-jira/README.md
docs/automations/standard/explain-code-experts/README.md
docs/automations/standard/review-todo-comments/README.md
docs/automations/welcome-newcomer/README.md

updated docs with quickstart metadata

meta update

---

docs/changelog.md
docs/cm-file.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18ZjlPZCkG402tTNHrEtGiAw0CDWnUjMk%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=MSOqgi0)

add regex to ignore repos

---

docs/automation-actions.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18dHGm0ncDw1sV3ISEtwEL5I1ZPkdRdI8%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=c64EaeF)

add github indication for wati fora all checks

---

docs/changelog.md
docs/cm-file.md
docs/execution-model.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1SOPMyG5jQrEJhwxwHHTdUg7h45zGRG4%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=rqq5th9)

triggers config

---

docs/automations/integrations/dependabot/approve-dependabot/README.md

reverse order of dependabot use cases to show risk aware first

---

.cm/notify-dev-team.cm

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19dApfyLaEhmLkLUKUjsypUEj7EsNeI%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=dBEZ2Pw)

Add dev team as a reviewers to docs

---

docs/execution-model.md

final version for release

---

docs/filter-functions.md

added lock files list and cleaned lagging white spaces

---

docs/automations/assign-team-members-as-reviewers/README.md
docs/automations/integrations/jira/configure/README.md
docs/automations/languages/html/README.md
docs/downloads/automation-library/integrations/github-actions/skip-github-action/skip_github_action_branch.cm
docs/downloads/automation-library/integrations/github-actions/skip-github-action/skip_github_action_label.cm
docs/downloads/automation-library/integrations/github-actions/skip-github-action/skip_github_action_resource.cm
docs/downloads/automation-library/integrations/slack/slack_send_notification.cm
docs/downloads/automation-library/integrations/zapier/zapier_export_pr_reviewers.cm
docs/downloads/automation-library/standard/review-assignment/notify_watcher.cm

fixed broken example CMs due to indentation issues

fix wrong indentation

---

docs/cm-file.md
docs/execution-model.md

1. add the triggers section to the cm file syntax page, 
2. reorder the triggres docs
3. provide an example with entire CM context

Triggers docs improvements 

---

docs/execution-model.md

fix markdown

---

docs/gitlab-installation.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1p8jN4OUSIXOou4UfE4CBl3hCsmaWob70%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=F-miIow)

remove gitlab single repo

---

docs/github-installation.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19zu1bqTecni8qLRTXdxiy7eLj1zARTVZE%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=R2nsJPf)

Removed docker from GitHub installation

---

docs/execution-model.md

added some better texts

---

docs/automation-actions.md

new arg to explaincodeExperts

---

docs/automation-actions.md

Action update desc

---

docs/automation-actions.md

concat_mode

---

docs/automations/approve-tests/README.md
docs/automations/integrations/copilot/flag-copilot-pr/README.md
docs/automations/integrations/dependabot/approve-dependabot/README.md
docs/automations/integrations/orca/review-orca-alerts/README.md
docs/automations/integrations/renovate/approve-renovate/README.md
docs/automations/integrations/sonar/label-sonar/README.md
docs/automations/provide-estimated-time-to-review/README.md
docs/automations/request-screenshot/README.md
docs/automations/standard/label-management/label-unresolved-threads/README.md
docs/automations/standard/link-issue-tracker/README.md
docs/automations/welcome-newcomer/README.md

nothing visible - just metadata changes

add and remove quickstart

---

docs/automation-actions.md

new update-title action

---

docs/context-variables.md

added pr source

---

docs/custom-github-app.md

GitHub server more fixes

---

docs/custom-github-app.md

moved tips

---

docs/downloads/automation-library/integrations/github-actions/dispatch-github-action/dispatch_github_action_branch.cm
docs/downloads/automation-library/integrations/github-actions/dispatch-github-action/dispatch_github_action_label.cm
docs/downloads/automation-library/integrations/github-actions/dispatch-github-action/dispatch_github_action_resource.cm
docs/downloads/automation-library/integrations/terraform/review_terraform_module_name.cm

Change of automation names so it better fits the description and have a unique name per automation.

fix names to be unique and match the docs

---

docs/custom-github-app.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1JuqHotJoaGFulaCD5TbygYVKQ8neraA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=QHzLAAW)

allowlist ips for Github App

---

docs/cm-file.md

Admin restrictions

---

docs/automation-actions.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1971nzbkmylqYk3yCaQlrqV9BisMd8A3vQ%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=jVeuNNr)

add thread documentation

---

docs/troubleshooting.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1zI2P5GOhWjoD0scrg6vCKXhG7VRby5Jk%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=M8iR4hl)

added troubleshooting

---

docs/execution-model.md

add dependabot example to triggers reference 

---

docs/plugins.md
mkdocs.yml

- make async more visible on the side panel for discovery. 
- add tips for escaped chars.

improve plugin sections

---

docs/automations/generate-pr-description/README.md

fix typo "

---

docs/filter-functions.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19kwS1iYdjpBQE8JTuGlgmibpEuGZcLS4U%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=sgtDYJN)

Decode and encode

---

.cm/ask-ai.cm
docs/filter-functions.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1WHV6UezovmGnXFBMPG59Vbkv7E7rFV0k%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=S2wJZWH)

added rule to describe pr

---

docs/downloads/automation-library/integrations/askAI/askAI_CR.cm
docs/downloads/automation-library/integrations/askAI/askAI_summarize.cm
docs/downloads/automation-library/integrations/askAI/askAI_tests.cm
plugins/filters/askAI/askAI.cm
plugins/filters/askAI/index.js
plugins/filters/askAI/reference.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1zbDPEAI3R7TxViWVgybyrHzQKsdVCRU%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=eJFMwft)

added role to askAI plugin + examples

---

docs/context-variables.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18cWmvVYGCwsl7TJMKQltZzIjAHq3qQfjo%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=MhMDSb3)

Context variable fixes

---

docs/context-variables.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1RxLkAWk88PZb4lwgZJyhsC8sWYx9iZk%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=sXSEUn4)

Update check context

---

docs/downloads/automation-library/integrations/jira/jira_update_field.cm

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1u6znXVhw0x19k7LpFCcRrR8XFpKnYRpE%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=NF10dSq)

add missing tickets variable

---

docs/filter-functions.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX14awSlIcMOy2O7Huip5T5O44wGa61rss%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=ShYvLfk)

fix capture return type

---

docs/execution-model.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1YaGoFdNOQNSlTOoLkTlIlmH7p182rArw%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=idFN08y)

fix texts in execution

---

docs/bitbucket-installation.md
docs/context-variables.md
mkdocs.yml

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18tTZxuchlVDsS9IQ7WdkiFmfPxf8d8jOE%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Pl1jZdm)

minor fixes for BB

---

plugins/filters/askAI/reference.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1dfcXheiH9yC4N1ObtvZfuOeiciuQr4%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=siT21WF)
___
- Changed "Authorization and Data Sharing" note title to "Security note"
- Added warning about potential API costs
- Enhanced emphasis on data sensitivity warning with bold text
Purpose: To improve security awareness and cost transparency for users of the askAI plugin integration.
**Please rate this `askLB` description:**

change note title and add bold

---

docs/gitlab-installation.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1EJmGwOIeL6W1Wjjut8TJ4M4oObpvV0%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=UXd37Ce)
___
Purpose: Update GitLab installation documentation to correctly reference GitLab-specific terminology and connection process.
Main changes:
- Changed "Install the gitStream service" to "Connect gitStream in LinearB"
- Fixed incorrect references to Bitbucket, replacing them with GitLab
- Updated mention of "code review workflows" to "Merge Request workflows"
**Please rate this `LinearB_AI` description:**

Remove-BB-mention-on-GL

---

docs/automations/integrations/LinearBAI/describe-pr/README.md
docs/filter-functions.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1xZV0GoMnEYMuOr0gRknX9fAiGaZddU%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=0Wvrla9)
Purpose: Documents that the AI_DescribePR feature is a premium functionality, requiring a paid account to access LinearB's AI service.
Main changes:
- Adds premium feature indicator and notice to AI_DescribePR documentation
- Updates the note section to indicate which features require paid accounts

added icon and note

---

docs/automations/integrations/LinearBAI/describe-pr/README.md

Purpose: Minor text improvements to the Premium Feature note section in the LinearB AI PR description documentation.
Main changes:
- Changed "filter" to "automation" for more accurate terminology
- Removed redundant "to learn more" phrase from sales team contact link

fix note in automation

---

docs/automations/approve-safe-changes/README.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX199nhnlg99g22hdiyBLHyFsnel3mkI2Ds%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=gddTBn6)
Purpose: Updates the documentation to explicitly include images as part of safe changes that can be automatically approved.
Main changes:
- Added "images" to the list of PR content types that qualify for automatic approval
*This description was generated by LinearB AI and added by gitStream*.

add images to safe changes

---

docs/automation-actions.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX11JhFCyeEY8xRbrW49I3FcS0NPHzexww%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=S8bT_x6)
Purpose: Added a new 'add-code-comment' action to gitStream that allows adding comments to specific lines of code in pull requests.
Main changes:
- Added documentation for 'add-code-comment' action with required parameters: comment text and file path
- Supports optional start_line and end_line parameters for targeting specific code lines
- Includes example usage showing how to add a code review comment
<sub>AI-generated content may contain inaccuracies. Please verify before …

Code coment action

---

docs/automations/integrations/askAI/add-tests/README.md
docs/automations/integrations/askAI/code-review/README.md
docs/downloads/automation-library/integrations/LinearBAI/code-review.cm

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1m3b1vuvzl5MYicI2QuoFaVXLWDuWs8us%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://moontower.gitstream.cm/v2/badge/collaboration-page?magicLinkId=k1Ec0jQ)
Purpose: Remove 'starter_kits: [genai]' from documentation files and clean up configuration files for AI-powered code review automations.
Main changes:
- Removed 'starter_kits: [genai]' line from two README.md files in askAI documentation
- Cleaned up trailing dots in LinearBAI code-review.cm configuration file

remove askAI from starter kit

---

docs/automation-actions.md
docs/downloads/automation-library/integrations/LinearBAI/code-review.cm
docs/downloads/automation-library/integrations/LinearBAI/describe-pr.cm

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19UrsHR19EpMMcAwkeWmUzhz086Obr2yI%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://moontower.gitstream.cm/v2/badge/collaboration-page?magicLinkId=FnLrSFy)
- Purpose: Update LinearB AI automation names and syntax for better clarity and consistency across documentation and example files
- Main changes:
- Renamed automation from 'pr_description' to 'linearb_ai_description' for clearer identification
- Changed syntax from 'pr.draft == false' to 'not pr.draft' for cleaner code
- Updated comments formatting for consistency
<sub>AI-generated content may contain inaccuracies. Please verify before using. **[We’d love your …

LINBEE-15412 align linearb ai docs

---

docs/github-installation.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19mb7Mr5hEzo5dkFAn7dXo4snGarQlSw%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://moontower.gitstream.cm/v2/badge/collaboration-page?magicLinkId=45MulD0)
Purpose: Updates the formatting of IP addresses in the Prerequisites section of the GitHub installation documentation.
Main changes:
- Adjusts indentation and spacing of IP addresses in Prerequisites section for better readability

gh allowlist

---

docs/automation-actions.md

Purpose: Updates documentation to extend `code-review` and `describe-changes` actions support for GitLab and Bitbucket, and adds new customization parameters.
Main changes:
- Added GitLab and Bitbucket support for code-review and describe-changes actions
- Added 'guidelines' parameter to code-review action for custom AI instructions
- Added 'guidelines' and 'template' parameters to describe-changes action for PR description customization

Update AI actions with all providers, template and guidelines 

---

docs/automations/integrations/LinearBAI/code-review/README.md

This PR updates the documentation to include a hyperlink for the 'code-review' action in the LinearB AI integration guide.
Main changes:
- Adds a hyperlink to the 'code-review' action, directing users to the automation actions page.

Add link to code-review action docs

---

docs/faq.md

This PR updates the FAQ section to provide better guidance for users encountering issues with gitStream.
Main changes:
- Adds a reference to a Troubleshooting page for common problems
- Includes direct support contact information (support@linearb.io) for unresolved issues

link to support instead of github issues

---

docs/integrations/LinearBAI.md
docs/integrations/README.md

Purpose: Rename LinearB AI integration file and add user commands documentation reference in markdown files.
Main changes:
- Renamed documentation file from LB_AI.md to LinearBAI.md
- Updated reference link in README.md to match new filename
- Added user commands documentation section with cross-references to user-commands.md

replace LB_AI so only LinearBAI is used
