docs/cm-file.md, docs/github-installation.md, docs/gitlab-installation.md, docs/how-it-works.md, docs/index.md
depends on #84
I pulled the docs to fix spelling and got distracted by inconsistent formatting in markdown. I recommend setting up some blocking pipeline with markdownlint. My personal choice is trunk.io (free) but there are plenty of alternatives.
or at least setting up your editors to trim trailing whitespace. VSCode settings: 
```json
"files.trimTrailingWhitespace": true,
"files.insertFinalNewline": true,
"files.trimFinalNewlines": true,
```
- spelling fixes
- some formatting changes
=> some formatting fixes

docs/automation-actions.md
Assigning a team as a PR reviewer only works if that team already has write access to the repo.
=> Add tip about enabling write access

.cm/gitstream.cm
1. Approve docs changes by maintainers, so they are not blocked.
2. Notify maintainers on new PRs
3. Mark changes to automation rule examples as they need to be tested and working
=> Update automation rules

docs/cm-file.md
New feature, org level admins:
> When added in the `cm` repository (i.e. at the organizational level), the specified users obtain administrative privileges to CM changes across every repository in the organization. Consequently, for every pull request that modifies a CM file in any of the repositories, the `config.admin.users` parameters are drawn from both the pull request repository and the `cm` repository.
=> describe admin rules

docs/dry-run-mode.md
In dry run mode, you should get comments every time you commit a change so you can see the result of every change and compare to the previous result. The change in docs make it more clear.
=> explain comments in dry run

README.md
To run the documentation server locally using Python3, follow these steps:
1. Create a virtual environment named `.venv` using the command `python -m venv .venv`
2. Activate the virtual environment by running the command `. ./.venv/bin/activate`
3. Install the required packages by executing `pip install -r requirements.txt`
4. Start the server by running `mkdocs serve`
The local documentation server should now be running at `http://127.0.0.1:8000/`.
=> local documentation server setup

docs/faq.md
in the FAQ:
in package control:
=> point to the CM syntax definitions for ST4

docs/integrations/README.md
I forgot to update the URLs on the integrations page to work when they are embedded in other pages.
=> Fix Integrations page URLs for embedding

docs/automations/approve-javascript-formatting-change/README.md, docs/automations/approve-python-formatting-change/README.md, docs/automations/approve-safe-changes/README.md, docs/automations/approve-team-by-directory/README.md, docs/automations/approve-tiny-changes/README.md, docs/integrations/javadoc.md, docs/integrations/jit.md, docs/integrations/jsdoc.md, docs/integrations/sonar.md, docs/snippets/automation-footer.md, docs/snippets/general.md, docs/snippets/safe-merge-automation.md, mkdocs.yml
Changes include:
* Removed direct links to individual integration automations from their respective integration landing page. This was throwing off the site structure and creates too many small pages on the site.
* Created some snippets we can use at the bottom of the automation examples to provide helpful resources and beef up the SEO value of key automation examples that are light on word count. I want to see how this impacts our SEO and potentially roll something similar out to more automation examples.
* General site config updates in the mkdocs.yml file to add links and improve overall site SEO.
=> SEO fixes: optimize automation example pages.

mkdocs.yml
This enables a built-in feature to display a button to edit the page you're viewing on GitHub. This will be super helpful when fixing small errors on pages.
=> Add GitHub edit button

docs/stylesheets/extra.css
=> fix integration cards borders for light mode

docs/downloads/automation-library/standard/enforce_pr_title.cm
1. removed trailing or (pipe), as before the fix it match also nothing as TYPE
2. added missing trailing slash as the pattern should be wrapped with 2 slash, r//
=> fixed the correctness of the regex

docs/downloads/automation-library/additional_review_for_large_pr.cm
I was recently going through the setup of gitStream and went to implement the [Additional reviewers for large PRs](https://docs.gitstream.cm/automations/additional-review-for-large-pr/) example and found that the provided `.cm` didn't have quite the right formatting on one line. There was some additional indentation for the `args` line that was breaking teh run.
After comparing to the rest of the downloads and verifying the change works in our application, this submission is for those also going through this setup in the future.
=> Corrected indentation in "Additional Reviews for large PR" example

docs/faq.md
Resolving one typo and one missing verb in the docs. Forked for the PR as I don't have perms to create a branch on the main repo; please let me know if there is a preferred alternative way for me to handle this.
=> FAQ typo fix

docs/automations/automation-library.md
These links are dead. The content has been moved to other locations in the docs so I'm removing them from here.
=> Remove dead links

docs/integrations/README.md
This is required to make the link work when the integrations page is embedded into other locations.
=> change linearb Integration link to fully-qualified filepath

.cm/gitstream.cm, docs/how-it-works.md
1. fix wrong link that use `.com` instead of `.cm`
2. add rules to prevent `gitstream.com` and any use of links with `localhost`
=> Fix prevent com

plugins/filters/getCodeowners/README.md
This fixes an issue with how this content renders when imported into other locations.
=> Reorder getCodeowners readme

docs/downloads/automation-library/standard/review-todo-comments/review_todo_comments.cm
Fix by checking for `+` at the begening of the regex, was checked on these PRs:
1. PR with new line that starts with `# TODO:` - automation was executed
2. PR with existing line that start with `# TODO:` - automation was not executed
3. PR with removed line that start with `# TODO:` - automation was not executed
=> Fix TODO cm so it will show a comment only for newly added TODO

docs/execution-model.md
=> fix typo in example

docs/downloads/automation-library/standard/review-todo-comments/review_todo_comments.cm
I encountered an issue in a project I'm contributing to: gitStream would request changes saying my PR has a todo in it, even though I didn't add any todos. I asked another team member if they know what the issue is, and they figured it out: our todo regex was copied from the example in the docs, and that example is incorrect. The current example:
```js
/^[+].*(TODO)|(todo)/
```
It matches:
1. either a line starting with a plus sign, followed by any amount of any characters, followed by `TODO` (uppercase)
2. or it matches any line that has `todo` (lowercase) in it, ignoring the `^[+].*` part
Because of the second part, it reacted to a todo comment I had deleted. This PR fixes this issue by placing both variants (`TODO` and `todo`) inside the same group.
Demo on regex101: [before the …
=> Fix todo example

docs/custom-github-app.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1rBgnnmDi8PQ4mdNnJo1ZPp1EeFC5N58%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=_viO8dm)
fix typo in path of `.gitstream`
=> fix typo in path of `.gitstream`

docs/github-installation.md
Changed the spacing from 8 to 4 spaces in the admonition section to render the images and links rather than codeblocks containing markdown.
**Before fix**
**After fix**
=> fix github-installation.md to display images

automations/README.md
I prepended `https://` to the automation docs link so it points to the docs webpage rather than a null page in the repo.
=> fixed link in automations/README.md

docs/automations/standard/branch-management/README.md, docs/automations/standard/branch-management/enforce-branch-name/README.md, docs/automations/standard/label-management/README.md, docs/automations/standard/label-management/enforce-labels/README.md, docs/automations/standard/label-management/label-approvals/README.md, docs/automations/standard/label-management/label-modified-resources/README.md, docs/automations/standard/label-management/label-prs-by-language/README.md, docs/automations/standard/label-management/label-resources-percent/README.md, docs/automations/standard/label-management/label-unresolved-threads/README.md, docs/automations/standard/label-management/suggest-labels/README.md
- Fixes #463 
- Fixes formatting so that there is now a single header per example for:
- https://docs.gitstream.cm/automations/standard/branch-management/ 
- https://docs.gitstream.cm/automations/standard/label-management/ 
- Adds footers that are consistent with the parent page to:
- https://docs.gitstream.cm/automations/standard/branch-management/enforce-branch-name
- https://docs.gitstream.cm/automations/standard/label-management/enforce-labels
- https://docs.gitstream.cm/automations/standard/label-management/label-approvals
- https://docs.gitstream.cm/automations/standard/label-management/label-modified-resources
- https://docs.gitstream.cm/automations/standard/label-management/label-prs-by-language
- https://docs.gitstream.cm/automations/standard/label-management/label-resources-perce …
=> Fix formatting issues on label-management & branch-management pages

docs/filter-functions.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1JKtCri5xhIgkjBpIcC0DFPWDlywVw8%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=4WCKorH)
=> ERT explanation

docs/downloads/javascript.cm, docs/downloads/organization.cm, docs/downloads/python.cm
Really simple fix to remove tabs from the cm files so that they are valid YAML.
Fixed files:
- docs/downloads/javascript.cm
- docs/downloads/organization.cm
- docs/downloads/python.cm
=> Fix formatting in cm files

docs/downloads/gitstream.cm
Grammatical error found in the GitStream docs configuration description
=> Fix Grammatical Error in GitHub Setup Docs

plugins/filters/askAI/index.js
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1F06WnQN0pRUSJxYX8qQi0E2lA3symx70%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=phmlc9w)
* Modified the `askAI` function to use the new constants and refactored the context building process to ensure only relevant files are included. Improved error handling by logging error messages from the API response.
=> Refactor askAI plugin: improve file exclusion logic and enhance conttext

docs/execution-model.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18WdlmY97UlfXbNzpxUM1ZUp1V0JUl9w%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=YvD9XlK)
=> trigggers-refinement

docs/bitbucket-installation.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19soDZDlDBp40g7HdV7LO7FY8Nu3Px8AGo%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=X8sKwei)
Purpose:
Updates the Bitbucket installation documentation to require a dedicated gitStream user account with specific naming convention.
Main changes:
- Adds new prerequisite requiring dedicated user with "gitstream" in the name
- Modifies user account section to specify naming requirement (must contain "gitstream")
- Simplifies language around user account configuration and permissions
=> enforce `gitstream` in bb user name

README.md
Purpose: Removes the Apache 2.0 license badge from the README.md header section.
Main changes:
- Deleted license badge and its associated hyperlink from the repository's README header
=> Remove license badge to avoid confusion

docs/execution-model.md, docs/faq.md, docs/index.md, docs/limits.md, mkdocs.yml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19cMp054oby6mx1bH8ROVbRsrnGs67rso%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=fnZuyPl)
Purpose: Introduces monthly automation limits for free gitStream accounts and explains what happens when limits are reached.
Main changes:
- Added new documentation page explaining free account PR automation limits and upgrade options
- Added warning notices about limits in FAQ and homepage
- Added details about limit behavior in execution model documentation (skipped checks, 90% warnings)
=> added info on limits

plugins/filters/askAI/index.js
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1fEfPgyRUxWJ7vhJWfgmGtlAiJTsveQA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=SQuC463)
Purpose: Adds support for uv.lock file to the list of lock files that should be excluded from AI analysis.
Main changes:
- Added 'uv.lock' to the LOCK_FILES array
*This description was generated by LinearB AI and added by gitStream*.
=> Add uv.lock to exclude list

plugins/filters/getCodeowners/get_codeowners.cm
Purpose: Rename the 'codeowners' filter to 'getCodeowners' for better clarity in functionality.
Main changes:
- Updated filter name from 'codeowners' to 'getCodeowners' in code ownership lookup functionality
=> Fix codeowners filter name to match filename

docs/integrations/README.md, docs/integrations/askAI.md
Purpose: Updates the documentation to clarify that users need to provide their own AI service API key and renames the askAI integration to "Bring Your Own AI".
Main changes:
- Renamed askAI integration to "Bring Your Own AI" in navigation and titles
- Added clarification about requiring user's own AI service API key
- Updated warning section with clearer plugin requirements
=> Rename AI integration to "Bring Your Own AI"

docs/automations/integrations/LinearBAI/describe-pr/README.md, docs/downloads/automation-library/integrations/LinearBAI/describe-pr.cm, docs/filter-functions.md
Purpose: Updates the PR description automation to use the new `describe-changes` action instead of the deprecated `AI_DescribePR` filter.
Main changes:
- Replaces `AI_DescribePR` filter with `describe-changes` automation action
- Adds filter to skip description for draft PRs
- Removes deprecated `AI_DescribePR` filter documentation
=> Update PR description docs to use describe-changes action

docs/custom-github-app.md
Purpose: Update the IP addresses required for network connection between GitHub Server and gitStream services.
Main changes:
- Replaced old IP 54.241.87.26 with new IP 13.56.203.235
- Replaced old IP 54.193.121.186 with new IP 54.151.81.98
=> Update gitStream connection IPs in custom GitHub app docs

docs/bitbucket-installation.md, docs/github-installation.md, docs/gitlab-installation.md
Purpose: Add network connectivity requirements to access gitStream's services for Bitbucket, GitHub, and GitLab installations.
Main changes:
- Added prerequisite: Allow network connections to IPs 13.56.203.235 and 54.151.81.98 for all platforms
- Updated installation documentation to include network requirements in each platform's prerequisites section
=> add to BB, GL, GH

docs/automation-actions.md
Purpose and impact: This PR adds information about automatically excluded files from code review and describe changes actions.
Main changes:
- Lists file types, extensions, and regular expressions for automatically excluded files
- Provides a table of lock files, programming languages, and package managers
- Adds a tip about filtering more files using config.ignore_files
=> Add excluded files documentation for code review and changes

docs/execution-model.md, mkdocs.yml
AI: Rename "Execution Model" to "Trigger Control" in docs
Document that `on` parameter can be used within individual automation blocks, while `triggers.include` and `triggers.exclude` are file-level only.
Purpose: This PR updates the Trigger Control documentation and renames the "Execution Model" section to "Trigger Control" for clarity.
Main changes:
- Renamed "Execution Model" to "Trigger Control" in docs and navigation
- Added a note about the usage of 'on' parameter and triggers.include/exclude
- Minor formatting and content adjustments throughout the document
=> Rename execution model documentation to trigger control

docs/automation-actions.md
AI no longer filters pipeline CI files, adds many binary & lock file exclusions, and organizes JS exclusions under better categories.
Purpose and impact: This PR expands the list of file types automatically excluded from code review and adds new regex patterns for filtering lock and build files.
Main changes:
- Adds numerous file extensions to the Data exclusion list
- Introduces new Lock and Build regex patterns for file exclusion
- Moves some existing regex patterns to more specific categories
=> Update excluded file types for code review

docs/downloads/gitStream-gl.cm, docs/gitlab-installation.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1gYZEjhZBiA23LThpF6Rp04tg0LBHRE%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://moontower.gitstream.cm/v2/badge/collaboration-page?magicLinkId=0gVDyXe)
This PR introduces a new gitStream configuration file for GitLab and updates the installation documentation accordingly.
Main changes:
- Adds a new gitStream configuration file (gitStream-gl.cm) with automations for GitLab
- Updates the GitLab installation documentation to reference the new configuration file
- Provides example configurations for various GitLab runner setups
<sub>AI-generated content may contain inaccuracies. Please verify before using. …
=> remove-triggers

docs/troubleshooting.md
- This PR adds troubleshooting guidance for gitStream failures related to special characters in template strings.
- Explains the issue of gitStream failing with YAML parsing errors due to special characters
- Provides a solution using Nunjucks multiline strings to escape special characters
- Adds an example of properly formatting template strings with special characters
=> added troubleshooting

docs/downloads/automation-library/integrations/dependabot/approve_dependabot.cm, docs/downloads/automation-library/integrations/dependabot/approve_dependabot_minor.cm, docs/execution-model.md, docs/stylesheets/extra.css, plugins/filters/extractDependabotVersionBump/extract_dependabot_version_bump.cm
Improve layout of triggers defaults
Bug: https://linearb.atlassian.net/browse/LINBEE-16194
Purpose: This PR adds explicit triggers to Dependabot-related automations and updates documentation on trigger control.
Main changes:
- Added 'on' triggers (pr_created and commit) to Dependabot automations
- Updated execution-model.md with detailed information on explicit triggers
- Adjusted CSS styling for trigger details in documentation
=> Add 'on' event triggers to Dependabot automation examples

docs/automations/standard/explain-code-experts/README.md, docs/downloads/automation-library/standard/explain_code_experts.cm, docs/downloads/gitStream-gl.cm, docs/downloads/github/gitstream.cm, docs/downloads/gitstream.cm, docs/downloads/sales_demo.cm
This PR updates the "Explain Code Experts" automation to trigger on specific events and only for PRs with a 'suggest-reviewer' label.
Main changes:
- Added explicit triggers for PR creation, ready for review, and new commits
- Changed condition to only run on PRs with 'suggest-reviewer' label
- Updated documentation to reflect new trigger conditions and label requirement
=> Add triggers to suggest-code-experts examples

docs/dry-run-mode.md
This PR enhances the documentation on testing gitStream automations, providing clearer guidance and introducing a new testing method.
Main changes:
- Restructures the content to focus on two testing methods: Dry Run Mode and Playground
- Clarifies the functionality and benefits of Dry Run Mode
- Introduces the gitStream Playground as an additional testing option
=> dry run improvements

docs/downloads/gitStream-gl.cm, docs/downloads/gitstream.cm
Purpose: Refactor bot detection logic in gitStream configuration files for improved maintainability.
Main changes:
- Introduce IS_NOT_A_BOT variable to centralize bot detection logic
- Replace inline bot detection checks with IS_NOT_A_BOT variable in automation conditions
- Expand bot detection list to include '_bot_' in addition to existing bot identifiers
=> Bot detection ai cm

docs/cm-file.md
Purpose: This PR enhances organization-level rule control in gitStream by introducing repository-specific inclusion and exclusion capabilities.
Main changes:
- Adds a section on controlling organization-level rules per repository using triggers
- Introduces repository inclusion and exclusion functionality using `triggers.include.repository` and `triggers.exclude.repository`
- Demonstrates how to create repository-type specific rules for different repository categories
=> Add repository filtering docs for organization-level rules

plugins/filters/extractDependabotVersionBump/index.js, plugins/filters/extractDependabotVersionBump/test.js
AI: I've enhanced the version extraction regex to handle both "Bumps" and "Updates" patterns in Dependabot PR descriptions and added comprehensive tests to verify functionality.
Purpose: This PR enhances the extractDependabotVersionBump plugin to handle both "Bumps" and "Updates" patterns in Dependabot PR descriptions.
Main changes:
- Updated regex to match both "Bumps" and "Updates" patterns
- Improved handling of trailing dots in version numbers
- Added comprehensive test cases to validate the changes
=> Improve Dependabot version extraction to support "Updates" pattern

docs/automations/integrations/copilot/flag-copilot-pr/README.md, docs/automations/integrations/cursor/flag-cursor-pr/README.md, docs/downloads/automation-library/integrations/copilot/copilot-instructions.md, docs/downloads/automation-library/integrations/copilot/label_copilot_by_rule.cm, docs/downloads/automation-library/integrations/cursor/cursor-ai-logging.mdc, docs/downloads/automation-library/integrations/cursor/label_cursor_by_rule.cm
Documentation: Add AI Rules section for Copilot and Cursor PRs
Enhance Dependabot version bump detection in plugins
Add AI tracking files for Copilot and Cursor tools
Purpose and impact: This PR introduces automated labeling for PRs assisted by AI tools (Copilot and Cursor) using a data-driven approach with structured logging.
Main changes:
- Adds "Label by AI Rules" option for both Copilot and Cursor, using `.cm/ai.log` file to track AI usage
- Introduces AI logging instructions for Copilot and Cursor to ensure consistent, structured logging
- Implements gitStream automation to label PRs as "ai-assisted" based on `.cm/ai.log` changes
<sub>AI-generated content may contain inaccuracies. Please verify before using. **[We'd love your …
=> Add AI Rules section for Copilot and Cursor PRs

docs/bitbucket-installation.md, docs/gitlab-installation.md
This PR updates documentation for Bitbucket and GitLab installations, clarifying limitations and adding warnings about unsupported features.
Main changes:
- Adds warning about unsupported 'triggers' and 'on' functionality in Bitbucket and GitLab
- Improves formatting and removes unnecessary whitespace
- Clarifies that labels are not supported in Bitbucket
=> update docs with bitbucket triggers warning

docs/automation-actions.md, docs/automations/integrations/LinearBAI/code-review/README.md, docs/automations/integrations/LinearBAI/describe-pr/README.md, docs/downloads/automation-library/integrations/LinearBAI/code-review-bb.cm, docs/downloads/automation-library/integrations/LinearBAI/code-review-gl.cm, docs/downloads/automation-library/integrations/LinearBAI/code-review.cm, docs/downloads/automation-library/integrations/LinearBAI/describe-pr-bb.cm, docs/downloads/automation-library/integrations/LinearBAI/describe-pr-gl.cm, docs/downloads/automation-library/integrations/LinearBAI/describe-pr.cm, docs/downloads/gitStream-gl.cm, docs/downloads/gitstream-bb.cm, docs/downloads/gitstream.cm
Purpose and impact: This PR updates the code review and describe changes automations to support multiple Git platforms (GitHub, GitLab, Bitbucket) and improves bot detection.
Main changes:
- Added platform-specific configuration files for code review and describe changes automations
- Updated bot detection logic to include '_bot_' in the list of bot identifiers
- Improved safe changes detection for automatic approvals
=> Add ai to defaults

docs/automations/integrations/copilot/flag-copilot-pr/README.md
- This PR fixes a typo in the documentation for GitHub Copilot PR labeling automation.
- Corrects the spelling of "which" in a warning message about experimental settings.
=> Fix typo on Copilot docs

docs/bitbucket-installation.md, docs/github-installation.md, docs/gitlab-installation.md
Purpose and impact: This PR adds detailed information about IP allowlisting for gitStream across GitHub, GitLab, and Bitbucket installations.
Main changes:
- Explains the importance of IP allowlisting for webhook event handling and CI runner requests
- Recommends adding LinearB/gitStream service IPs and using self-hosted runners with static IPs
- Provides context on potential IP-related errors and how to resolve them
=> Add detailed IP allowlisting explanation for all Git providers

docs/bitbucket-installation.md, docs/github-installation.md, docs/gitlab-installation.md
This PR improves the documentation for IP allowlisting in gitStream across multiple Git platforms.
Main changes:
- Adds detailed explanations about webhook event handling and outbound requests from CI runners
- Provides recommended solutions for ensuring reliable connections with gitStream
- Removes unnecessary blank lines and improves formatting consistency across platform-specific docs
=> fix the bullet list not showing up correctly

docs/automations/integrations/askAI/add-tests/README.md, docs/automations/integrations/askAI/code-review/README.md, docs/automations/integrations/askAI/document/README.md, docs/automations/integrations/askAI/improve/README.md, docs/automations/integrations/askAI/summarize-pr/README.md, docs/integrations/askAI.md
This PR adds a "search: exclude: true" parameter to multiple documentation files related to AI integrations in gitStream.
Main changes:
- Adds "search: exclude: true" to the front matter of five AI-related automation documentation files
- Adds the same parameter to the main AI integration documentation file
=> Exclude askAI docs from search results

docs/automation-actions.md, docs/automations/integrations/LinearBAI/code-review/README.md, docs/downloads/automation-library/integrations/LinearBAI/code-review-bb.cm, docs/downloads/automation-library/integrations/LinearBAI/code-review-gl.cm, docs/downloads/automation-library/integrations/LinearBAI/code-review.cm, docs/integrations/LB_AI.md
=> Improve instructions for adding code review guidelines

.cm/gitstream.cm
docs that where already apprvoed and correct
=> change link check so it match only new additions and do not alert on old

docs/execution-model.md
triggers exists and automation level explict triggers, the actual triggers used will be the result of unifing both lists
Purpose: Adds documentation on how file-level and automation-level triggers are unified in gitStream.
Main changes:
- Introduces a note explaining that file-level and automation-level triggers are combined through unification.
- Clarifies that automations will trigger on any event specified in either trigger list.
- Explains the behavior when both trigger types exist in the configuration.
=> in `Explicit triggers` that in the case that bith file level explict

docs/automation-actions.md, docs/downloads/automation-library/integrations/LinearBAI/code-review-bb.cm, docs/downloads/automation-library/integrations/LinearBAI/code-review-gl.cm, docs/downloads/automation-library/integrations/LinearBAI/code-review.cm, docs/downloads/automation-library/integrations/LinearBAI/describe-pr-bb.cm, docs/downloads/automation-library/integrations/LinearBAI/describe-pr-gl.cm, docs/downloads/automation-library/integrations/LinearBAI/describe-pr.cm, docs/downloads/gitStream-gl.cm, docs/downloads/gitstream-bb.cm, docs/downloads/gitstream.cm
Purpose: Add Renovate bot filtering to LinearB AI integrations for more precise automation control.
Main changes:
- Replaced single bot filter with separate bot_author and bot_branch properties
- Added branch name matching to identify Renovate branches in bot filtering
- Refactored bot detection condition from negative to positive logic across all templates
=> Add bot filtering to LinearB AI integrations

docs/execution-model.md
Add comprehensive documentation for gitStream's action-level execution control, explaining how and when specific actions are automatically skipped based on triggering events.
Purpose: Update execution model documentation to explain how gitStream intelligently controls action execution based on triggering events.
Main changes:
- Added detailed explanation of action-level execution control that automatically skips AI-powered and code-related actions
- Provided action execution rules table showing which actions only execute on code-related triggers
- Included practical examples demonstrating how explicit triggers override the automatic skip mechanism
<sub>AI-generated content may contain inaccuracies. Please verify before using. **[We'd love …
=> Update Execution Model Documentation for Action-Level Control

docs/execution-model.md
Purpose: Add warning notice that explicit trigger functionality is only available on GitHub and will cause failures on other platforms.
Main changes:
- Added warning block specifying that trigger parameters are GitHub-only features
- Clarified that omitting trigger configuration is required for GitLab and Bitbucket platforms
- Included error behavior information for using triggers on unsupported platforms
=> Emphasis triggers are supported for GitHub only

docs/automation-actions.md, docs/cm-file.md, docs/filter-functions.md
Purpose: Add documentation for new `git_history_since` configuration option to limit git history analysis for code expertise features.
Main changes:
- Added detailed configuration documentation with examples for the `git_history_since` parameter
- Updated configuration table to include the new git history limiting option
- Added cross-referenced tips in automation actions and filter functions documentation
=> Add documentation for new git history limiting configuration

docs/bitbucket-installation.md, docs/downloads/bitbucket-pipelines.yml
Purpose: Update Bitbucket installation documentation with comprehensive IP allowlisting instructions for various runner configurations.
Main changes:
- Renamed info section heading to "Advanced: IP Allowlisting for gitStream" for better categorization
- Added instruction to enable Atlassian IP ranges in bitbucket-pipeline.yml configuration
- Restructured pipeline example with clearly commented sections for both cloud and self-hosted runners
=> Update Bitbucket installation docs with IP allowlisting details

docs/user-commands.md
Purpose: Fix command and function name inconsistencies in the gitStream documentation for code experts feature.
Main changes:
- Changed command from `/gs code-experts` to `/gs experts` for improved usability
- Updated function reference from `explain_code_experts@v1` to `explain-code-experts@v1` for consistency
=> Fix hyphen in code_experts command

docs/managed-mode.md, mkdocs.yml
Purpose: Add documentation for LinearB's Managed Mode for AI automations including configuration details and available automation templates.
Main changes:
- Created new managed-mode.md document detailing LinearB's managed AI automations and configurations
- Added YAML examples for AI code review, PR descriptions, smart labeling, review time estimation, and dependabot automation
- Updated navigation menu to include Managed Mode documentation and reorganized GitHub Server documentation
=> Add docs for Managed Mode

docs/managed-mode.md
Update documentation with new dependabot auto-approve logic and rename
Purpose: Update documentation for dependabot automation and rename smart labeling section to accurately reflect its functionality.
Main changes:
- Renamed smart labeling section from "Claude Code Detection" to "Agent Coding Detection" for broader applicability
- Split dependabot automation documentation into separate "Minor Bump" and "Patch Bump" sections
- Removed unnecessary manifest version declaration from dependabot configuration example
- Added missing dependabot_bump template variable to the configuration example
=> Update dependabot and labeling automation docs
